"""init_db

Revision ID: b5c8c019753b
Revises: e6000cf58757
Create Date: 2024-05-10 11:52:47.369284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5c8c019753b'
down_revision = 'e6000cf58757'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
