"""nome_da_migration

Revision ID: e6000cf58757
Revises: e2f45b8ff421
Create Date: 2024-05-10 06:08:38.300492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6000cf58757'
down_revision = 'e2f45b8ff421'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
